# Generated by Django 5.2.7 on 2026-08-13 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='is_featured',
            field=models.BooleanField(default=True),
        ),
    ]
