# Generated by Django 5.2.7 on 2026-08-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0003_idea_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='idea_covers/'),
        ),
    ]
