# Generated by Django 5.2.7 on 2026-08-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0004_idea_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
