# Generated by Django 5.2.7 on 2026-08-16 12:26

import idea.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0005_idea_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='idea_covers/', validators=[idea.validators.validate_image_integrity]),
        ),
        migrations.AlterField(
            model_name='idea',
            name='document',
            field=models.FileField(upload_to='idea_docs/', validators=[idea.validators.validate_zip_integrity]),
        ),
    ]
